"""Puerto de persistencia de CreativeAuthoring."""

from typing import Protocol
from uuid import UUID

from app.creative_authoring.domain.models import Character, Scenario, Story, StoryPage, StyleProfile


class CreativeAuthoringRepository(Protocol):
    def add_character(self, value: Character) -> None: ...

    def get_character(self, item_id: UUID, owner_id: UUID) -> Character | None: ...

    def list_characters(self, owner_id: UUID, query: str | None = None) -> list[Character]: ...

    def save_character(self, value: Character) -> None: ...

    def delete_character(self, item_id: UUID, owner_id: UUID) -> bool: ...

    def add_scenario(self, value: Scenario) -> None: ...

    def get_scenario(self, item_id: UUID, owner_id: UUID) -> Scenario | None: ...

    def list_scenarios(self, owner_id: UUID, query: str | None = None) -> list[Scenario]: ...

    def save_scenario(self, value: Scenario) -> None: ...

    def delete_scenario(self, item_id: UUID, owner_id: UUID) -> bool: ...

    def add_style_profile(self, value: StyleProfile) -> None: ...

    def get_style_profile(self, item_id: UUID, owner_id: UUID) -> StyleProfile | None: ...

    def list_style_profiles(
        self, owner_id: UUID, query: str | None = None
    ) -> list[StyleProfile]: ...

    def save_style_profile(self, value: StyleProfile) -> None: ...

    def delete_style_profile(self, item_id: UUID, owner_id: UUID) -> bool: ...

    def add_story(self, value: Story) -> None: ...

    def get_story(self, item_id: UUID, owner_id: UUID) -> Story | None: ...

    def list_stories(self, owner_id: UUID, query: str | None = None) -> list[Story]: ...

    def save_story(self, value: Story) -> None: ...

    def delete_story(self, item_id: UUID, owner_id: UUID) -> bool: ...

    def add_page(self, value: StoryPage) -> None: ...

    def get_page(self, page_id: UUID, story_id: UUID, owner_id: UUID) -> StoryPage | None: ...

    def list_pages(self, story_id: UUID, owner_id: UUID) -> list[StoryPage]: ...

    def save_page(self, value: StoryPage, owner_id: UUID) -> None: ...

    def delete_page(self, page_id: UUID, story_id: UUID, owner_id: UUID) -> bool: ...

    def owns_characters(self, character_ids: list[UUID], owner_id: UUID) -> bool: ...
